spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/pathfinder?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${db_username}
    password: ${db_password}

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  sql:
    init:
      mode: never

  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
#Cloudinary Properties
#cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
    resources:
      static-locations: file:./src/main/resources/static/
      cache-period: 0